class CountryOption {
  final String name;
  final String isoCode;

  const CountryOption({required this.name, required this.isoCode});

  String get flagEmoji {
    final code = isoCode.toUpperCase();
    if (code.length != 2) return '';
    final first = code.codeUnitAt(0) - 65 + 0x1F1E6;
    final second = code.codeUnitAt(1) - 65 + 0x1F1E6;
    return String.fromCharCode(first) + String.fromCharCode(second);
  }
}

const List<CountryOption> allCountries = [
  CountryOption(name: 'Afghanistan', isoCode: 'AF'),
  CountryOption(name: 'Albania', isoCode: 'AL'),
  CountryOption(name: 'Algeria', isoCode: 'DZ'),
  CountryOption(name: 'Andorra', isoCode: 'AD'),
  CountryOption(name: 'Angola', isoCode: 'AO'),
  CountryOption(name: 'Antigua and Barbuda', isoCode: 'AG'),
  CountryOption(name: 'Argentina', isoCode: 'AR'),
  CountryOption(name: 'Armenia', isoCode: 'AM'),
  CountryOption(name: 'Australia', isoCode: 'AU'),
  CountryOption(name: 'Austria', isoCode: 'AT'),
  CountryOption(name: 'Azerbaijan', isoCode: 'AZ'),
  CountryOption(name: 'Bahamas', isoCode: 'BS'),
  CountryOption(name: 'Bahrain', isoCode: 'BH'),
  CountryOption(name: 'Bangladesh', isoCode: 'BD'),
  CountryOption(name: 'Barbados', isoCode: 'BB'),
  CountryOption(name: 'Belarus', isoCode: 'BY'),
  CountryOption(name: 'Belgium', isoCode: 'BE'),
  CountryOption(name: 'Belize', isoCode: 'BZ'),
  CountryOption(name: 'Benin', isoCode: 'BJ'),
  CountryOption(name: 'Bhutan', isoCode: 'BT'),
  CountryOption(name: 'Bolivia', isoCode: 'BO'),
  CountryOption(name: 'Bosnia and Herzegovina', isoCode: 'BA'),
  CountryOption(name: 'Botswana', isoCode: 'BW'),
  CountryOption(name: 'Brazil', isoCode: 'BR'),
  CountryOption(name: 'Brunei', isoCode: 'BN'),
  CountryOption(name: 'Bulgaria', isoCode: 'BG'),
  CountryOption(name: 'Burkina Faso', isoCode: 'BF'),
  CountryOption(name: 'Burundi', isoCode: 'BI'),
  CountryOption(name: 'Cabo Verde', isoCode: 'CV'),
  CountryOption(name: 'Cambodia', isoCode: 'KH'),
  CountryOption(name: 'Cameroon', isoCode: 'CM'),
  CountryOption(name: 'Canada', isoCode: 'CA'),
  CountryOption(name: 'Central African Republic', isoCode: 'CF'),
  CountryOption(name: 'Chad', isoCode: 'TD'),
  CountryOption(name: 'Chile', isoCode: 'CL'),
  CountryOption(name: 'China', isoCode: 'CN'),
  CountryOption(name: 'Colombia', isoCode: 'CO'),
  CountryOption(name: 'Comoros', isoCode: 'KM'),
  CountryOption(name: 'Congo', isoCode: 'CG'),
  CountryOption(name: 'Costa Rica', isoCode: 'CR'),
  CountryOption(name: 'Croatia', isoCode: 'HR'),
  CountryOption(name: 'Cuba', isoCode: 'CU'),
  CountryOption(name: 'Cyprus', isoCode: 'CY'),
  CountryOption(name: 'Czech Republic', isoCode: 'CZ'),
  CountryOption(name: 'Democratic Republic of the Congo', isoCode: 'CD'),
  CountryOption(name: 'Denmark', isoCode: 'DK'),
  CountryOption(name: 'Djibouti', isoCode: 'DJ'),
  CountryOption(name: 'Dominica', isoCode: 'DM'),
  CountryOption(name: 'Dominican Republic', isoCode: 'DO'),
  CountryOption(name: 'Ecuador', isoCode: 'EC'),
  CountryOption(name: 'Egypt', isoCode: 'EG'),
  CountryOption(name: 'El Salvador', isoCode: 'SV'),
  CountryOption(name: 'Equatorial Guinea', isoCode: 'GQ'),
  CountryOption(name: 'Eritrea', isoCode: 'ER'),
  CountryOption(name: 'Estonia', isoCode: 'EE'),
  CountryOption(name: 'Eswatini', isoCode: 'SZ'),
  CountryOption(name: 'Ethiopia', isoCode: 'ET'),
  CountryOption(name: 'Fiji', isoCode: 'FJ'),
  CountryOption(name: 'Finland', isoCode: 'FI'),
  CountryOption(name: 'France', isoCode: 'FR'),
  CountryOption(name: 'Gabon', isoCode: 'GA'),
  CountryOption(name: 'Gambia', isoCode: 'GM'),
  CountryOption(name: 'Georgia', isoCode: 'GE'),
  CountryOption(name: 'Germany', isoCode: 'DE'),
  CountryOption(name: 'Ghana', isoCode: 'GH'),
  CountryOption(name: 'Greece', isoCode: 'GR'),
  CountryOption(name: 'Grenada', isoCode: 'GD'),
  CountryOption(name: 'Guatemala', isoCode: 'GT'),
  CountryOption(name: 'Guinea', isoCode: 'GN'),
  CountryOption(name: 'Guinea-Bissau', isoCode: 'GW'),
  CountryOption(name: 'Guyana', isoCode: 'GY'),
  CountryOption(name: 'Haiti', isoCode: 'HT'),
  CountryOption(name: 'Honduras', isoCode: 'HN'),
  CountryOption(name: 'Hungary', isoCode: 'HU'),
  CountryOption(name: 'Iceland', isoCode: 'IS'),
  CountryOption(name: 'India', isoCode: 'IN'),
  CountryOption(name: 'Indonesia', isoCode: 'ID'),
  CountryOption(name: 'Iran', isoCode: 'IR'),
  CountryOption(name: 'Iraq', isoCode: 'IQ'),
  CountryOption(name: 'Ireland', isoCode: 'IE'),
  CountryOption(name: 'Israel', isoCode: 'IL'),
  CountryOption(name: 'Italy', isoCode: 'IT'),
  CountryOption(name: 'Jamaica', isoCode: 'JM'),
  CountryOption(name: 'Japan', isoCode: 'JP'),
  CountryOption(name: 'Jordan', isoCode: 'JO'),
  CountryOption(name: 'Kazakhstan', isoCode: 'KZ'),
  CountryOption(name: 'Kenya', isoCode: 'KE'),
  CountryOption(name: 'Kiribati', isoCode: 'KI'),
  CountryOption(name: 'Kuwait', isoCode: 'KW'),
  CountryOption(name: 'Kyrgyzstan', isoCode: 'KG'),
  CountryOption(name: 'Laos', isoCode: 'LA'),
  CountryOption(name: 'Latvia', isoCode: 'LV'),
  CountryOption(name: 'Lebanon', isoCode: 'LB'),
  CountryOption(name: 'Lesotho', isoCode: 'LS'),
  CountryOption(name: 'Liberia', isoCode: 'LR'),
  CountryOption(name: 'Libya', isoCode: 'LY'),
  CountryOption(name: 'Liechtenstein', isoCode: 'LI'),
  CountryOption(name: 'Lithuania', isoCode: 'LT'),
  CountryOption(name: 'Luxembourg', isoCode: 'LU'),
  CountryOption(name: 'Madagascar', isoCode: 'MG'),
  CountryOption(name: 'Malawi', isoCode: 'MW'),
  CountryOption(name: 'Malaysia', isoCode: 'MY'),
  CountryOption(name: 'Maldives', isoCode: 'MV'),
  CountryOption(name: 'Mali', isoCode: 'ML'),
  CountryOption(name: 'Malta', isoCode: 'MT'),
  CountryOption(name: 'Marshall Islands', isoCode: 'MH'),
  CountryOption(name: 'Mauritania', isoCode: 'MR'),
  CountryOption(name: 'Mauritius', isoCode: 'MU'),
  CountryOption(name: 'Mexico', isoCode: 'MX'),
  CountryOption(name: 'Micronesia', isoCode: 'FM'),
  CountryOption(name: 'Moldova', isoCode: 'MD'),
  CountryOption(name: 'Monaco', isoCode: 'MC'),
  CountryOption(name: 'Mongolia', isoCode: 'MN'),
  CountryOption(name: 'Montenegro', isoCode: 'ME'),
  CountryOption(name: 'Morocco', isoCode: 'MA'),
  CountryOption(name: 'Mozambique', isoCode: 'MZ'),
  CountryOption(name: 'Myanmar', isoCode: 'MM'),
  CountryOption(name: 'Namibia', isoCode: 'NA'),
  CountryOption(name: 'Nauru', isoCode: 'NR'),
  CountryOption(name: 'Nepal', isoCode: 'NP'),
  CountryOption(name: 'Netherlands', isoCode: 'NL'),
  CountryOption(name: 'New Zealand', isoCode: 'NZ'),
  CountryOption(name: 'Nicaragua', isoCode: 'NI'),
  CountryOption(name: 'Niger', isoCode: 'NE'),
  CountryOption(name: 'Nigeria', isoCode: 'NG'),
  CountryOption(name: 'North Korea', isoCode: 'KP'),
  CountryOption(name: 'North Macedonia', isoCode: 'MK'),
  CountryOption(name: 'Norway', isoCode: 'NO'),
  CountryOption(name: 'Oman', isoCode: 'OM'),
  CountryOption(name: 'Pakistan', isoCode: 'PK'),
  CountryOption(name: 'Palau', isoCode: 'PW'),
  CountryOption(name: 'Palestine', isoCode: 'PS'),
  CountryOption(name: 'Panama', isoCode: 'PA'),
  CountryOption(name: 'Papua New Guinea', isoCode: 'PG'),
  CountryOption(name: 'Paraguay', isoCode: 'PY'),
  CountryOption(name: 'Peru', isoCode: 'PE'),
  CountryOption(name: 'Philippines', isoCode: 'PH'),
  CountryOption(name: 'Poland', isoCode: 'PL'),
  CountryOption(name: 'Portugal', isoCode: 'PT'),
  CountryOption(name: 'Qatar', isoCode: 'QA'),
  CountryOption(name: 'Romania', isoCode: 'RO'),
  CountryOption(name: 'Russia', isoCode: 'RU'),
  CountryOption(name: 'Rwanda', isoCode: 'RW'),
  CountryOption(name: 'Saint Kitts and Nevis', isoCode: 'KN'),
  CountryOption(name: 'Saint Lucia', isoCode: 'LC'),
  CountryOption(name: 'Saint Vincent and the Grenadines', isoCode: 'VC'),
  CountryOption(name: 'Samoa', isoCode: 'WS'),
  CountryOption(name: 'San Marino', isoCode: 'SM'),
  CountryOption(name: 'Sao Tome and Principe', isoCode: 'ST'),
  CountryOption(name: 'Saudi Arabia', isoCode: 'SA'),
  CountryOption(name: 'Senegal', isoCode: 'SN'),
  CountryOption(name: 'Serbia', isoCode: 'RS'),
  CountryOption(name: 'Seychelles', isoCode: 'SC'),
  CountryOption(name: 'Sierra Leone', isoCode: 'SL'),
  CountryOption(name: 'Singapore', isoCode: 'SG'),
  CountryOption(name: 'Slovakia', isoCode: 'SK'),
  CountryOption(name: 'Slovenia', isoCode: 'SI'),
  CountryOption(name: 'Solomon Islands', isoCode: 'SB'),
  CountryOption(name: 'Somalia', isoCode: 'SO'),
  CountryOption(name: 'South Africa', isoCode: 'ZA'),
  CountryOption(name: 'South Korea', isoCode: 'KR'),
  CountryOption(name: 'South Sudan', isoCode: 'SS'),
  CountryOption(name: 'Spain', isoCode: 'ES'),
  CountryOption(name: 'Sri Lanka', isoCode: 'LK'),
  CountryOption(name: 'Sudan', isoCode: 'SD'),
  CountryOption(name: 'Suriname', isoCode: 'SR'),
  CountryOption(name: 'Sweden', isoCode: 'SE'),
  CountryOption(name: 'Switzerland', isoCode: 'CH'),
  CountryOption(name: 'Syria', isoCode: 'SY'),
  CountryOption(name: 'Taiwan', isoCode: 'TW'),
  CountryOption(name: 'Tajikistan', isoCode: 'TJ'),
  CountryOption(name: 'Tanzania', isoCode: 'TZ'),
  CountryOption(name: 'Thailand', isoCode: 'TH'),
  CountryOption(name: 'Timor-Leste', isoCode: 'TL'),
  CountryOption(name: 'Togo', isoCode: 'TG'),
  CountryOption(name: 'Tonga', isoCode: 'TO'),
  CountryOption(name: 'Trinidad and Tobago', isoCode: 'TT'),
  CountryOption(name: 'Tunisia', isoCode: 'TN'),
  CountryOption(name: 'Turkey', isoCode: 'TR'),
  CountryOption(name: 'Turkmenistan', isoCode: 'TM'),
  CountryOption(name: 'Tuvalu', isoCode: 'TV'),
  CountryOption(name: 'Uganda', isoCode: 'UG'),
  CountryOption(name: 'Ukraine', isoCode: 'UA'),
  CountryOption(name: 'United Arab Emirates', isoCode: 'AE'),
  CountryOption(name: 'United Kingdom', isoCode: 'GB'),
  CountryOption(name: 'United States', isoCode: 'US'),
  CountryOption(name: 'Uruguay', isoCode: 'UY'),
  CountryOption(name: 'Uzbekistan', isoCode: 'UZ'),
  CountryOption(name: 'Vanuatu', isoCode: 'VU'),
  CountryOption(name: 'Vatican City', isoCode: 'VA'),
  CountryOption(name: 'Venezuela', isoCode: 'VE'),
  CountryOption(name: 'Vietnam', isoCode: 'VN'),
  CountryOption(name: 'Yemen', isoCode: 'YE'),
  CountryOption(name: 'Zambia', isoCode: 'ZM'),
  CountryOption(name: 'Zimbabwe', isoCode: 'ZW'),
];
